// <auto-generated />
namespace RC.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewStuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewStuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201502200337446_New-Stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
